import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (

    <div className="absolute inset-0 w-full h-screen z-[100] flex-center">
      <div className="back-gradient -z-1" />
      {children}
    </div>
  );
}
